name: Place Validations Functionality Sanity Tests

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  sanity:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven


      
    - name: fetch working directory report
      run: pwd

    - name: Build with Maven
      run: mvn test --file pom.xml -Dcucumber.filter.tags="@Addplace" -Dcucumber.features="src/test/java/feature/placevalidations.feature"
      
    - name: upload regression artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Test-Output
        path: ./test-output/

    - name: fetch the directory
      run: ls -al /home/runner/work/autdemo/autdemo/test-output

  download-artifacts:
    runs-on: ubuntu-latest
    needs: sanity

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Download previous report
      uses: actions/download-artifact@v4
      with:
        name: Test-Output

    - name: Fetch the directory
      run: ls -al /home/runner/work/autdemo/autdemo/test-output

env:
  ACTIONS_RUNNER_DEBUG: true
  ACTIONS_STEP_DEBUG: true
