name: Place Validations Functionality Sanity Tests

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  sanity:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven


      
    - name: fetch working directory report
      run: pwd

    - name: Build with Maven
      run: mvn test --file pom.xml -Dcucumber.filter.tags="@Addplace" -Dcucumber.features="src/test/java/feature/placevalidations.feature"

    - name: Create stor artifacts for sanity test
      run: mkdir -p ./test-output/sanity

    - name:  move to  correct directory
      run: mv ./test-output/* ./test-output/sanity

    - name: List sanity directory contents
      run: ls -al ./test-output/sanity/

    
    - name: upload regression artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Test-Output
        path: ./test-output/sanity/

    - name: fetch the directory
      run: ls -al ./test-output/sanity/
  download-artifacts:
    runs-on: ubuntu-latest
    needs:  sanity

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Create directory for consolidated reports
      run: mkdir -p ./consolidated-reports

    - name: Download previous report
      uses: actions/download-artifact@v4
      with:
        name: Test-Output
        path: ./consolidated-reports/sanity

    - name: Fetch the directory
      run: ls -al ./consolidated-reports/

env:
  ACTIONS_RUNNER_DEBUG: true
  ACTIONS_STEP_DEBUG: true
